pipeline {    
    agent {
        label 'slave'
    }  

    parameters{
        choice(
            name: 'Branch name',
            choices: ['dev','main','prod'],
            description: 'Select your branch'
            )
    }

    stages{
        stage('Server date'){
            steps{
                sh 'date'
            }
        }
        stage('Ip Address'){
            steps{
                sh 'hostname -I'
            }
        }
        stage('Cpu Details'){
            steps{
                sh 'lscpu'
            }
        }
        stage('Disk Usage'){
            steps{
                sh 'du -h'
            }
        }
        stage('Memory usage'){
            steps{
                sh 'free -h'
            }
        }
        stage('Partition Details'){
            steps{
                sh 'lsblk'
            }
        }
    }
}
